#!/bin/bash
# start script for container
# note that the entrypoint of the parent image is not activated anymore

echo "WELCOME TO DXSTACK1-SYNCED"


sh webapp/start.sh
sh lsyncd/start.sh
sh phpmyadmin/start.sh
sh php-fpm/start.sh
sh nginx/start.sh
sh redis/start.sh
sh memcached/start.sh
sh mariadb/start.sh

echo "All services started."

# start a foreground process to keep the container running
exec bash --login