
DELETE FROM mysql.user WHERE user='';
FLUSH PRIVILEGES;


CREATE USER '${DX_MYSQL_USER}'@'%' IDENTIFIED BY '${DX_MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON * . * TO '${DX_MYSQL_USER}'@'%';
FLUSH PRIVILEGES;